Support paginated responses for GH get_repository_collaborators
obelisk/plaid pull request #20
Opened 2024-09-04 19:24 UTC by michelemin

This PR adds support for paginated responses from the GitHub API when fetching a repo's collaborators. See [the docs](https://docs.github.com/en/rest/collaborators/collaborators?apiVersion=2022-11-28#list-repository-collaborators) for more details about that endpoint.

The main idea is that we will always make a GET call with query params `page` and `per_page`. If these params are not given, then we default to 1 and 30, respectively (which are the defaults used by GH).

The existing `get_repository_collaborators` in plaid-stl has been marked as deprecated, and `get_all_repository_collaborators` has been added.

TODO:

- [ ] Testing
  - [ ] Check returned body for an empty page (condition to stop looping)
  - [ ] Double-check the return value (`Vec<String>` where each entry is a page) is what we want

2024-09-10 02:09 UTC, obelisk commented
Major comment would be to deserialize the data into a Vec<GitHubUser> or similar which will make it much easier for the consumer.

2024-09-10 18:54 UTC, michelemin commented on plaid/resources/plaid.toml
> +default = 300
Tested with a repository which had 361 collaborators, and I was hitting the memory limit.

2024-09-10 20:43 UTC, obelisk requested changes
Can you also clarify the backwards compatibility of this? I don't care if it's not backwards compatible, just want to know if rules need to be recompiled or not

2024-09-10 20:43 UTC, obelisk commented on plaid-stl/src/github/mod.rs
> +    r#type: String,
Generally I prefer `type_` and when used with serde you can use a rename directive. That just means that we prevent having `r#` throughout the codebase.

Also I think these variables need to be marked `pub` so they can be accessed by calling rules.

2024-09-10 20:43 UTC, obelisk commented on plaid-stl/src/github/mod.rs
> +struct Permission {
I think this also needs to be pub

2024-09-10 21:01 UTC, michelemin commented
> Can you also clarify the backwards compatibility of this? I don't care if it's not backwards compatible, just want to know if rules need to be recompiled or not

Added in the PR's comment

2024-09-11 21:17 UTC, obelisk approved these changes

2024-09-11 21:17 UTC, merged