Support adding error context for Plaid runtime + panic hook
obelisk/plaid pull request #37
Opened 2024-10-23 13:51 UTC by michelemin

This PR adds the following:
* A way for modules to give the Plaid runtime more context about errors they encounter. This is achieved by setting an error context (a `String`) which is then included in the error returned by the runtime.
* A simple panic hook (see [docs](https://doc.rust-lang.org/std/panic/fn.set_hook.html)) that, when a panic occurs, sets an appropriate context.

Note - The panic hook has been tested and works for things like explicit `panic!` and `index out of bounds`, but does not seem to work for OOM errors. For this reason, the explanation for an unknown error defaults to "This is probably an OOM error", since this is the only case we know of where the hook is not triggered and an explanation is not available.

### Impact
**! This change forces all rules to be modified and recompiled !** in order to support the new error management mechanism.

The return type of the `main` function must be `Result<(), XYZ>` where `XYZ` is something (most likely an enum) that implements `Error` (empty impl is fine) and `Display`.

2024-10-26 13:35 UTC, obelisk requested changes

2024-10-26 13:35 UTC, obelisk commented on plaid-stl/src/lib.rs
> +                plaid::set_error_context(panic_info.to_string());
This is always going to fail if you receive an OOM since it allocates.

2024-10-26 13:35 UTC, obelisk commented on plaid-stl/src/plaid/mod.rs
> +pub fn set_error_context(context: impl Display) {
In this case, I would have this take an &str to prevent allocations when calling this function

2024-10-26 13:35 UTC, obelisk commented on plaid/src/executor/mod.rs
> +                                .unwrap_or("> empty <".to_string()),
I'd just use None instead of `> empty <` unless you have a further reason to depart from the standard `Option` verbiage.

2024-10-28 12:45 UTC, michelemin commented on plaid-stl/src/lib.rs
> +        impl<'a> std::fmt::Write for NoAllocBuffer<'a> {
For clarity: I asked ChatGPT to come up with a non-allocating version of the code I had before.
I tested this code but we still end up with "This is probably an OOM", which is the default message when everything else fails.

2024-10-30 05:10 UTC, obelisk requested changes

2024-10-30 05:10 UTC, obelisk commented on plaid-stl/src/lib.rs
> +            let mut buffer = [0u8; 512]; // Stack-allocated buffer
I'm worried this could still be heap allocated depending on the compiler. I would move this allocation outside the closure then capture it. That will ensure that even if it is heap allocated, it happens before memory becomes a problem (at least in theory).

2024-10-30 23:20 UTC, obelisk commented on plaid-stl/src/lib.rs
> +macro_rules! set_panic_hook {
I think this can be simplified but we can come back to it

2024-10-30 23:20 UTC, obelisk approved these changes

2024-10-30 23:20 UTC, merged